### ISSUE TITLE
[Admin] Rename for Division, Class

### ISSUE THREAD

**Issue by oberak** [oberak/tup_edu_erp#1]
'Division' to 'Program Year'
'Class' to 'Batch'
'Class Division' to 'Class'

**Comment by MinNyiThatTant** [comment]
For sample,
Division=> 1BE, 2BE, 3BE ....... (Program Year)
Class=> 2019-IT, 2019-Civil ..... (Batch)
Class Division=> 2019-IT-1BE (or) 1BE-2019-IT ..... (Class)
